# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Local Active Chapter Constitution
description: > # this means to ignore newlines until "timezone:"
  Local Constitution of Triangle Fraternity at Michigan Technological University
timezone: America/Detroit

# Build settings
remote_theme: trianglefraternitymtu/governing-docs-theme
markdown: kramdown

plugins:
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - README.md
  - .travis.yml
  - .gitignore
  - LICENSE
